#!/bin/bash
# shellcheck source=/dev/null

# This is mostly a copy of "set_maven_promote_maven" in SonarSource/sonarlint-eclipse!

set -euo pipefail

source cirrus-env PROMOTE
source .cirrus/set_maven_build_version "$BUILD_NUMBER"
cirrus_jfrog_promote

if [[ ! -v GITHUB_TOKEN ]]; then
    echo "GITHUB_TOKEN is not set"
else
    BUILD_URL="${ARTIFACTORY_URL}/webapp/#/builds/${PROJECT}/${BUILD_NUMBER}/"
    curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H 'Content-Type: application/json' --data '{"state": "success", "target_url": "'"${BUILD_URL}"'", "description": "Latest promoted build: '"${PROJECT_VERSION}"'", "context": "repox"}' https://api.github.com/repos/"${GITHUB_REPO}"/statuses/"${GIT_SHA1}"
fi
