#!/bin/bash

# This is mostly a copy of "set_maven_build_version" in SonarSource/sonarlint-eclipse!
# Adjusted to remove unnecessary stuff not needed for the Eclipse RedDeer build.

set -euo pipefail

BUILD_ID=$1
CURRENT_VERSION=$(maven_expression "project.version")
RELEASE_VERSION=${CURRENT_VERSION%"-SNAPSHOT"}
NEW_VERSION="$RELEASE_VERSION.$BUILD_ID"

echo "Replacing version $CURRENT_VERSION with $NEW_VERSION"

mvn -B -e -V org.eclipse.tycho:tycho-versions-plugin:3.0.5:set-version -Dtycho.mode=maven -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false

export PROJECT_VERSION=$NEW_VERSION
