# You might wonder why this is here despite this being a Java/Maven/Tycho project. It is here for
# the GitHub Release Action to not fail on the releasability check for the Parent POM and
# QualityGate steps.
