name: Release
on:
  release:
    types:
      - published

# TODO: Replace the action with the released version and remove the `dryRun` option

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@task/tha/SLE-1057_Checksum
    with:
      publishToBinaries: true
      skipPythonReleasabilityChecks: true
      slackChannel: squad-ide-eclipse
