name: Release
on:
  release:
    types:
      - published

# TODO: Replace this with the final version of the GitHub Release Action that include the necessary changes!

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@34d8b20d125bfd58d124e84b007d3a18e61c358a # 5.10.4
    with:
      publishToBinaries: true
      slackChannel: squad-ide-eclipse
