name: Release
on:
  release:
    types:
      - published

# TODO: Replace the action with the released version and remove the `dryRun` option

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@85404e53633341038269d1757142cebfd0341df0
    with:
      publishToBinaries: true
      skipPythonReleasabilityChecks: true
      slackChannel: squad-ide-eclipse
      dryRun: true
