name: Release
on:
  release:
    types:
      - published

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@v6
    with:
      publishToBinaries: true
      skipPythonReleasabilityChecks: true
      slackChannel: C02E6L5C01H # squad-devex-private
      pushToDatadog: false
